apiVersion: apps/v1
kind: Deployment
metadata: 
  name: url-shortener-deployment
spec:
  replicas: 2
  selector:
    matchLables:
      app:url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: url-shortener:latest
          ports:
            - containerPort: 3000
