---
- name: Deploy URL Shortener Application
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - nodejs
          - npm
        state: present
    - name: Clone the repository
      git:
        repo: https://github.com/sksohail19/URL-Shortener.git
        dest: /opt/URL-Shortener

    - name: Install npm packages
      command: npm Install
      args:
        chdir: /opt/URL-Shortener
      
    - name: Build and run the application with docker.io
      docker_contianer:
        name: url_shortener
        image: url-shortener:lastest
        state: started
        build:
          path: /opt/URL-Shortener
        ports:
          - "3000:3000"
